"""Add credit_line field to User model

Revision ID: 3747260c1145
Revises: ae576e33d7dc
Create Date: 2021-02-10 09:17:47.539238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3747260c1145'
down_revision = 'ae576e33d7dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(
        'credit_line', sa.String(length=254), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'credit_line')
    # ### end Alembic commands ###
