"""ImageModel new size fields

Revision ID: 8266ee15773c
Revises: 3747260c1145
Create Date: 2021-02-16 15:38:46.154186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8266ee15773c'
down_revision = '3747260c1145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_model', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('image_model', sa.Column('orientation', sa.String(length=10), nullable=True))
    op.add_column('image_model', sa.Column('width', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_model', 'width')
    op.drop_column('image_model', 'orientation')
    op.drop_column('image_model', 'height')
    # ### end Alembic commands ###
