"""Agrega campo modified_on a articulo

Revision ID: d23a8c5c3f02
Revises: 8266ee15773c
Create Date: 2021-04-16 15:43:36.953335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23a8c5c3f02'
down_revision = '8266ee15773c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('modified_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'modified_on')
    # ### end Alembic commands ###
