"""modelos iniciales

Revision ID: ae576e33d7dc
Revises: 
Create Date: 2021-01-26 14:31:21.070272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae576e33d7dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('role',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('article',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('headline', sa.String(length=512), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('credit_line', sa.String(length=160), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('board_id', sa.String(length=60), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['board_id'], ['board.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_created_on'), 'article', ['created_on'], unique=False)
    op.create_table('image_model',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('upload_by', sa.String(length=32), nullable=True),
    sa.Column('store_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['upload_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('record_id', sa.String(length=32), nullable=True),
    sa.Column('role_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('role_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('permission')
    op.drop_table('image_model')
    op.drop_index(op.f('ix_article_created_on'), table_name='article')
    op.drop_table('article')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('board')
    # ### end Alembic commands ###
