name: CI

on: push

jobs:
  
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python --version
          pip install --upgrade build
          python -m build
          ls -l dist

  build-win32:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: ['x64', 'x86']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: ${{ matrix.arch }}
      - run: |
          python --version
          pip install --upgrade build
          python -m build
          ls -l dist
