name: CI

on: push

jobs:

  build-statics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Build styles
        run: |
          npm install -g sass
          cd styles
          yarn install 
          yarn run build && cd ..
      - name: Build javascript
        run: |
          cd jsclient 
          yarn install
          yarn run build && cd ..
  
  build-linux:
    needs: build-statics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Make executable
        run: |
          pip install --upgrade build pip
          python -m build
          ls -l dist

  build-win32:
    needs: build-statics
    runs-on: windows-latest
    strategy:
      matrix:
        arch: ['x64', 'x86']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: ${{ matrix.arch }}
      - name: Make executable
        run: |
          pip install --upgrade build pip
          python -m build
          ls -l dist
